import Link from "next/link";
import { EntrySearch } from "@/components/EntrySearch";
import { getAllManifestEntries, getAllTags } from "@/lib/entries";

export const metadata = {
  title: "Dev Lab | Daily developer knowledge",
  description:
    "A self-growing knowledge base of practical developer tips, patterns, and runnable snippets.",
};

export default function DevIndexPage() {
  const entries = getAllManifestEntries();
  const tags = getAllTags();

  return (
    <div className="min-h-screen bg-zinc-50 dark:bg-black">
      <header className="border-b border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-950">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-6">
          <div>
            <p className="text-sm font-medium uppercase tracking-[0.2em] text-zinc-500">
              Dev Lab
            </p>
            <h1 className="mt-1 text-3xl font-semibold tracking-tight text-zinc-900 dark:text-zinc-50">
              Daily developer knowledge
            </h1>
            <p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-600 dark:text-zinc-400">
              Practical notes, patterns, and runnable snippets generated by an
              honest auto-commit pipeline. Every entry is buildable and useful.
            </p>
          </div>
          <Link
            href="/"
            className="hidden rounded-full border border-zinc-200 px-4 py-2 text-sm font-medium text-zinc-700 transition hover:bg-zinc-50 dark:border-zinc-800 dark:text-zinc-300 dark:hover:bg-zinc-900 sm:inline-flex"
          >
            Home
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-6 py-10">
        <EntrySearch entries={entries} tags={tags} />
      </main>
    </div>
  );
}
